version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - gocyclo
    - errcheck
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 25
    errcheck:
      check-type-assertions: true
      check-blank: false
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      # defer xxx.Close() errors are intentionally ignored — standard Go pattern
      - linters: [errcheck]
        source: "^\\s+defer .*\\.Close\\(\\)"
    paths:
      - vendor/
