run:
  timeout: 5m

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: vendor/.*
      linters:
        - "*"

linters:
  enable:
    - govet
    - gocyclo
    - errcheck
  disable:
    - lll # Disable long line linter
